from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import MSO_AUTO_SIZE
import matplotlib.pyplot as plt
import os

def applyThemeColors(theme):
    if theme == 'Corporate':
        return RGBColor(0, 51, 102), RGBColor(240, 244, 248) # Dark Blue, Light Gray bg
    elif theme == 'Dark Modern':
        return RGBColor(255, 255, 255), RGBColor(30, 30, 30) # White, Dark bg
    elif theme == 'Startup Pitch':
        return RGBColor(220, 38, 38), RGBColor(255, 255, 255) # Red, White bg
    elif theme == 'Minimal':
        return RGBColor(50, 50, 50), RGBColor(255, 255, 255) # Dark Gray, White bg
    else: # Academic
        return RGBColor(0, 0, 0), RGBColor(255, 255, 255)

def apply_theme(slide, title_shape, body_shape, theme):
    primary_color, bg_color = applyThemeColors(theme)
    
    # Apply background color
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = bg_color
    
    if title_shape and title_shape.has_text_frame:
        title_frame = title_shape.text_frame
        title_frame.word_wrap = True
        title_frame.auto_size = MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE
        for paragraph in title_frame.paragraphs:
            paragraph.font.name = 'Segoe UI' if theme in ['Corporate', 'Startup Pitch', 'Dark Modern'] else 'Georgia'
            paragraph.font.color.rgb = primary_color
            paragraph.font.bold = True
                
    if body_shape and body_shape.has_text_frame:
        body_frame = body_shape.text_frame
        body_frame.word_wrap = True
        body_frame.auto_size = MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE
        for paragraph in body_frame.paragraphs:
            paragraph.font.name = 'Segoe UI' if theme in ['Corporate', 'Startup Pitch', 'Dark Modern'] else 'Georgia'
            # Base size, but auto_size shrinks if needed
            paragraph.font.size = Pt(20)
            if theme == 'Dark Modern':
                paragraph.font.color.rgb = RGBColor(220, 220, 220)
            else:
                paragraph.font.color.rgb = RGBColor(50, 50, 50)

def generate_chart_image(output_path, theme, chart_data=None):
    if chart_data and 'labels' in chart_data and 'values' in chart_data:
        labels = chart_data['labels']
        values = chart_data['values']
        title = chart_data.get('title', 'Performance Metrics Validation')
    else:
        labels = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
        values = [0.95, 0.92, 0.89, 0.91]
        title = 'Performance Metrics Validation'

    colors = ['#4F46E5', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6'][:len(labels)]
    
    if theme == 'Dark Modern':
        plt.style.use('dark_background')
    else:
        plt.style.use('default')

    plt.figure(figsize=(6, 4))
    plt.bar(labels, values, color=colors, edgecolor='none', alpha=0.9)
    plt.title(title, fontsize=14, pad=15)
    
    # Try dynamic ylim if it looks like percentages
    if all(isinstance(v, (int, float)) for v in values) and all(v <= 1.0 for v in values):
        plt.ylim(0, 1)
        
    # Hide top and right spines
    ax = plt.gca()
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, transparent=True)
    plt.close()
    return output_path

def create_presentation(json_data: dict, theme: str, output_filepath: str):
    prs = Presentation()
    # Ensure slide size is widescreen
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = json_data.get("title", "AI Presentation")
    subtitle.text = "Generated by AI Engine with Imagen"
    apply_theme(slide, title, subtitle, theme)

    # Content Slides
    from services.gemini_service import generate_slide_image

    for slide_data in json_data.get('slides', []):
        layout_type = slide_data.get('layout_type', 'standard')
        
        # Decide Base Layout
        if slide_data.get('contains_metrics') or layout_type == 'split_image':
            slide_layout = prs.slide_layouts[3] # Two content layout
        elif layout_type == 'three_column':
            slide_layout = prs.slide_layouts[5] # Title only, we draw shapes
        else:
            slide_layout = prs.slide_layouts[1] # Standard Bullet
            
        slide = prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        title.text = slide_data.get('title', 'Slide Title')
        
        # Presenter Notes
        notes_slide = slide.notes_slide
        text_frame = notes_slide.notes_text_frame
        text_frame.text = slide_data.get('notes', '')

        if layout_type == 'three_column':
            # Custom Drawing 3 Columns
            apply_theme(slide, title, None, theme)
            primary_color, bg_color = applyThemeColors(theme)
            
            # Text color calculation
            text_color = RGBColor(220, 220, 220) if theme == 'Dark Modern' else RGBColor(50, 50, 50)
            
            top = Inches(1.8)
            width = Inches(3.8)
            height = Inches(4.5)
            lefts = [Inches(0.8), Inches(4.8), Inches(8.8)]
            
            columns = slide_data.get('columns', [])
            for i, col_data in enumerate(columns[:3]):
                left = lefts[i]
                
                # Title Box
                txBox = slide.shapes.add_textbox(left, top, width, Inches(0.8))
                tf = txBox.text_frame
                tf.word_wrap = True
                p = tf.add_paragraph()
                p.text = col_data.get('header', '')
                p.font.bold = True
                p.font.size = Pt(22)
                p.font.color.rgb = primary_color
                
                # Content Box
                bodyBox = slide.shapes.add_textbox(left, top + Inches(0.8), width, height - Inches(0.8))
                bf = bodyBox.text_frame
                bf.word_wrap = True
                bp = bf.add_paragraph()
                bp.text = col_data.get('text', '')
                bp.font.size = Pt(18)
                bp.font.color.rgb = text_color
        else:
            # Handle Bullets for standard/split layout
            if len(slide.placeholders) > 1:
                body_shape = slide.placeholders[1]
                tf = body_shape.text_frame
                tf.clear()
                for idx, bullet in enumerate(slide_data.get('bullets', [])):
                    p = tf.add_paragraph()
                    p.text = bullet
                    p.level = 0
                    p.space_after = Pt(14)
                apply_theme(slide, title, body_shape, theme)
            else:
                apply_theme(slide, title, None, theme)
                
            # Right side Media (Chart or Image)
            if slide_data.get('contains_metrics') or layout_type == 'split_image':
                media_path = os.path.join(os.path.dirname(output_filepath), 'temp_media.jpg')
                has_media = False
                
                if slide_data.get('contains_metrics'):
                    chart_data = slide_data.get('chart_data')
                    generate_chart_image(media_path, theme, chart_data)
                    has_media = True
                elif layout_type == 'split_image' and slide_data.get('image_prompt'):
                    print(f"Generating image for: {slide_data.get('image_prompt')}")
                    success = generate_slide_image(slide_data.get('image_prompt'), media_path)
                    has_media = success
                
                if has_media and len(slide.placeholders) > 2:
                    img_shape = slide.placeholders[2]
                    slide.shapes.add_picture(media_path, img_shape.left, img_shape.top, width=img_shape.width)
                    try:
                        os.remove(media_path)
                    except:
                        pass

    prs.save(output_filepath)
    return output_filepath
